"""empty message

Revision ID: 221da1500d7d
Revises: d76c3b62ed85
Create Date: 2021-08-24 15:28:47.085738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221da1500d7d'
down_revision = 'd76c3b62ed85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitch', ['pitch_id'], ['id'])
    op.add_column('pitch', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'posted')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
